/**
 * M03: Local Visual Perception — Coordinate Parsing & Normalization
 * Author: AI003 (Visual Perception Engineer)
 * Authority: INTERFACES.md, docs/system-design/SYSTEM-DESIGN.md, docs/employees/AI003.md (§5)
 */

import {
  BoundingBox,
  CoordinateParsingError,
  RawVisualPrediction,
  ViewportMetadata,
} from './types';

export interface CoordinateParseOptions {
  viewport: ViewportMetadata;
  defaultPointSize?: number;
  scaleOverride?: 'unit' | 'thousand';
}

/**
 * Standardize and parse coordinates produced by ShowUI-2B into strict BoundingBox coordinates
 * matching the target browser viewport dimensions.
 */
export class CoordinateParser {
  private readonly viewport: ViewportMetadata;
  private readonly defaultPointSize: number;

  constructor(options: CoordinateParseOptions) {
    if (!options.viewport || options.viewport.width <= 0 || options.viewport.height <= 0) {
      throw new CoordinateParsingError('Invalid viewport dimensions for coordinate mapping', {
        viewport: options.viewport,
      });
    }
    this.viewport = options.viewport;
    this.defaultPointSize = options.defaultPointSize ?? 32;
  }

  /**
   * Determine whether coordinates are in [0, 1000] scale (ShowUI standard) or [0, 1] unit scale
   */
  public detectScale(coords: number[]): 'unit' | 'thousand' {
    const maxVal = Math.max(...coords);
    if (maxVal > 1.0) {
      return 'thousand';
    }
    return 'unit';
  }

  /**
   * Convert normalized [0, 1] or [0, 1000] coordinates into absolute viewport pixels
   */
  public parsePredictionToBoundingBox(prediction: RawVisualPrediction): BoundingBox {
    const raw = prediction.coordinates;

    if (!Array.isArray(raw) || (raw.length !== 2 && raw.length !== 4)) {
      throw new CoordinateParsingError(
        `Malformed prediction coordinates: expected array of length 2 or 4, received ${JSON.stringify(raw)}`,
        { prediction }
      );
    }

    for (const val of raw) {
      if (typeof val !== 'number' || Number.isNaN(val) || !Number.isFinite(val)) {
        throw new CoordinateParsingError(
          `Invalid coordinate value: expected finite number, received ${String(val)}`,
          { prediction }
        );
      }
    }

    const scale = prediction.coordinateScale ?? this.detectScale(raw);
    const denominator = scale === 'thousand' ? 1000 : 1.0;

    if (raw.length === 2) {
      // Point grounding: [x, y]
      const [normX, normY] = raw;
      const pixelCenterX = (normX / denominator) * this.viewport.width;
      const pixelCenterY = (normY / denominator) * this.viewport.height;

      return this.createBoxFromCenterPoint(pixelCenterX, pixelCenterY);
    } else {
      // Box grounding: ShowUI typically outputs [ymin, xmin, ymax, xmax] or [xmin, ymin, xmax, ymax]
      // Standardize detection based on order
      const [c0, c1, c2, c3] = raw;

      // In ShowUI / Qwen-VL architecture, boxes are [ymin, xmin, ymax, xmax]
      // Check if c0 <= c2 and c1 <= c3 to support standard ymin/xmin or xmin/ymin
      const normYmin = Math.min(c0, c2) / denominator;
      const normYmax = Math.max(c0, c2) / denominator;
      const normXmin = Math.min(c1, c3) / denominator;
      const normXmax = Math.max(c1, c3) / denominator;

      const x = Math.round(normXmin * this.viewport.width);
      const y = Math.round(normYmin * this.viewport.height);
      const width = Math.round((normXmax - normXmin) * this.viewport.width);
      const height = Math.round((normYmax - normYmin) * this.viewport.height);

      return this.clampBox({ x, y, width, height });
    }
  }

  /**
   * Parse text output generated by ShowUI VLM into structured predictions.
   * Supports:
   * 1. Python/JSON action dictionaries: `{'action': 'CLICK', 'position': [0.73, 0.21]}`,
   *    `{'action': 'SELECT_TEXT', 'position': [[0.1, 0.2], [0.8, 0.9]]}`
   * 2. Bounding boxes: `[ymin, xmin, ymax, xmax]`, `<box>[120, 340, 160, 680]</box>`
   * 3. Coordinate points: `[x, y]`, `<point>[x, y]</point>`, `Point: (250, 480)`
   */
  public parseTextResponse(responseText: string): RawVisualPrediction[] {
    if (!responseText || typeof responseText !== 'string') {
      return [];
    }

    const predictions: RawVisualPrediction[] = [];

    // Helper to check if coordinates are already captured
    const isAlreadyCaptured = (coords: number[]) => {
      return predictions.some((p) => {
        if (p.coordinates.length !== coords.length) return false;
        return p.coordinates.every((val, idx) => Math.abs(val - coords[idx]) < 1e-4);
      });
    };

    // Pattern 0: ShowUI Python/JSON action dictionaries
    // e.g. {'action': 'CLICK', 'value': None, 'position': [0.73, 0.21]}
    // e.g. {"action": "INPUT", "value": "search", "position": [0.5, 0.3]}
    // e.g. {'action': 'SELECT_TEXT', 'position': [[0.1, 0.2], [0.8, 0.9]]}
    const actionDictRegex = /\{['"]action['"]\s*:\s*['"]([A-Z_]+)['"](?:[^}]*?['"]position['"]\s*:\s*(\[\[[^\]]+\]\s*,\s*\[[^\]]+\]\]|\[[^\]]+\]))?[^}]*\}/gi;
    let dictMatch: RegExpExecArray | null;

    while ((dictMatch = actionDictRegex.exec(responseText)) !== null) {
      const actionName = dictMatch[1].toUpperCase();
      const posString = dictMatch[2];

      if (posString) {
        // Check if two-point box: [[x1, y1], [x2, y2]]
        const twoPointMatch = /\[\s*\[\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\]\s*,\s*\[\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\]\s*\]/.exec(posString);
        if (twoPointMatch) {
          const x1 = parseFloat(twoPointMatch[1]);
          const y1 = parseFloat(twoPointMatch[2]);
          const x2 = parseFloat(twoPointMatch[3]);
          const y2 = parseFloat(twoPointMatch[4]);
          // Standardize to [ymin, xmin, ymax, xmax]
          const coords: [number, number, number, number] = [
            Math.min(y1, y2),
            Math.min(x1, x2),
            Math.max(y1, y2),
            Math.max(x1, x2),
          ];
          if (!isAlreadyCaptured(coords)) {
            predictions.push({
              coordinates: coords,
              label: actionName,
              confidence: 0.9,
            });
          }
          continue;
        }

        // Check if single point: [x, y]
        const singlePointMatch = /\[\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\]/.exec(posString);
        if (singlePointMatch) {
          const px = parseFloat(singlePointMatch[1]);
          const py = parseFloat(singlePointMatch[2]);
          const coords: [number, number] = [px, py];
          if (!isAlreadyCaptured(coords)) {
            predictions.push({
              coordinates: coords,
              label: actionName,
              confidence: 0.9,
            });
          }
          continue;
        }
      }
    }

    // Pattern 1: Bounding boxes in brackets or tags: [ymin, xmin, ymax, xmax] or (ymin, xmin, ymax, xmax)
    const boxRegex = /(?:<box>|box:|\b)?\[?\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\]?(?:<\/box>)?/gi;
    let match: RegExpExecArray | null;

    while ((match = boxRegex.exec(responseText)) !== null) {
      const v0 = parseFloat(match[1]);
      const v1 = parseFloat(match[2]);
      const v2 = parseFloat(match[3]);
      const v3 = parseFloat(match[4]);

      const coords: [number, number, number, number] = [v0, v1, v2, v3];
      if (!isAlreadyCaptured(coords)) {
        predictions.push({
          coordinates: coords,
          label: 'visual_element',
          confidence: 0.85,
        });
      }
    }

    // Pattern 2: Point coordinates: point: (x, y) or <point>[x, y]</point> or standalone [x, y]
    const pointRegex = /(?:(?:point|click|target|position)[^0-9]*[[(]\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*[\])]|<point>\s*\[?\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\]?\s*<\/point>|^\s*\[\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\]\s*$)/gim;
    while ((match = pointRegex.exec(responseText)) !== null) {
      const pX = parseFloat(match[1] ?? match[3] ?? match[5]);
      const pY = parseFloat(match[2] ?? match[4] ?? match[6]);

      if (!Number.isFinite(pX) || !Number.isFinite(pY)) continue;

      // Ensure we don't duplicate if matched as part of a 4-coord box or existing point
      const alreadyInBox = predictions.some(
        (p) => p.coordinates.length === 4 && p.coordinates.includes(pX) && p.coordinates.includes(pY)
      );

      const coords: [number, number] = [pX, pY];
      if (!alreadyInBox && !isAlreadyCaptured(coords)) {
        predictions.push({
          coordinates: coords,
          label: 'interactable_point',
          confidence: 0.8,
        });
      }
    }

    return predictions;
  }

  /**
   * Constructs a clamped bounding box around a center click point
   */
  private createBoxFromCenterPoint(centerX: number, centerY: number): BoundingBox {
    const half = this.defaultPointSize / 2;
    const rawX = Math.round(centerX - half);
    const rawY = Math.round(centerY - half);
    const width = this.defaultPointSize;
    const height = this.defaultPointSize;

    return this.clampBox({ x: rawX, y: rawY, width, height });
  }

  /**
   * Strictly clamps bounding box to remain within the visible viewport bounds
   */
  public clampBox(box: BoundingBox): BoundingBox {
    const maxX = this.viewport.width;
    const maxY = this.viewport.height;

    const clampedX = Math.max(0, Math.min(box.x, maxX));
    const clampedY = Math.max(0, Math.min(box.y, maxY));

    // Ensure width and height do not extend beyond the viewport edge
    const availableWidth = Math.max(0, maxX - clampedX);
    const availableHeight = Math.max(0, maxY - clampedY);

    const clampedWidth = Math.max(0, Math.min(box.width, availableWidth));
    const clampedHeight = Math.max(0, Math.min(box.height, availableHeight));

    return {
      x: clampedX,
      y: clampedY,
      width: clampedWidth,
      height: clampedHeight,
    };
  }
}
